auth/urls.py
from django.urls import path

from auth.views import RegisterView

app_name = 'custom_auth'

urlpatterns = [
    path('sign-up/', RegisterView.as_view(), name='register'),
]

cart/urls.py
from django.urls import path

from cart.views import CartListView, delete_from_cart, change_product_view

app_name = 'cart'

urlpatterns = [
    path('', CartListView.as_view(), name='cart'),
    path('delete/<int:pk>/', delete_from_cart, name='delete'),
    path('change/<int:pk>/<int:count>/', change_product_view, name='change'),
]

catalog/urls.py
from django.urls import path

from catalog.views import product_details_view, ProductListView

app_name = 'catalog'

urlpatterns = [
    path('<int:product_id>/', product_details_view, name='detail'),
    path('list/', ProductListView.as_view(), name='list'),
]

e_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('catalog.urls', namespace='cat')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('auth/', include('auth.urls', namespace='auth'))
]

catalog/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=124, verbose_name='Название категории')

    class Meta:
        ordering = ('category_name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категорий'

    def __str__(self):
        return self.category_name


class Country(models.Model):
    country_name = models.CharField(max_length=32)

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'

    def __str__(self):
        return self. country_name

class Manufacturer(models.Model):
    manufacturer_name = models.CharField(max_length=32, verbose_name='Название производителя')
    address = models.CharField(max_length=124, verbose_name='Адрес производителя')
    phone = models.PositiveIntegerField(verbose_name='Номер телефона')
    country_name = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='Страна')

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.manufacturer_name


class Product(models.Model):
    product_name = models.CharField(max_length=64, verbose_name='Название продукта')
    manufacturer_name = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, verbose_name='Название производителя')
    guaranty = models.PositiveIntegerField(verbose_name='Гарантия')
    count = models.PositiveIntegerField(verbose_name='Количество')
    category_name = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Название категории')

    class Meta:
        ordering = ('product_name',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.product_name

catalog/forms.py
from django import forms


class Product2CartForm(forms.Form):
    count = forms.IntegerField(min_value=1)
    #product_id = forms.IntegerField(min_value=1, show_hidden_initial=True)

cart/views.py
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView

from cart.cart import Cart
from catalog.models import Product


# Create your views here.
class CartListView(ListView):
    model = Product
    template_name = 'cart/cart.html'
    context_object_name = 'products'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        cart = Cart(self.request)  # from cart.cart import Cart
        ids = list(map(int, list(cart.keys())))  # [1, 2, 3, 4]
        products = Product.objects.filter(id__in=ids)
        context[self.context_object_name] = products
        context['cart'] = self.request.session['cart']
        return context


def change_product_view(request, pk, count):
    cart = Cart(request)
    cart[str(pk)] = str(count)
    return JsonResponse({})


def delete_from_cart(request, pk):
    if not request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        raise PermissionDenied()
    cart = Cart(request)
    try:
        del cart[str(pk)]
    except KeyError as e:
        return JsonResponse({'successed': False})  # json serializable
    return JsonResponse({'successed': True})

catalog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from cart.cart import Cart
from .forms import Product2CartForm
from .models import Product


def product_details_view(request, product_id):
    prod = get_object_or_404(Product, id=product_id)
    cart = Cart(request)

    if request.method == 'POST':
        form = Product2CartForm(request.POST)
        if form.is_valid():
            # count = form.cleaned_data['count']
            cart[str(product_id)] = form.cleaned_data['count']
            form = Product2CartForm()
    else:
        form = Product2CartForm()

    if str(product_id) in cart.session['cart'].keys():
        in_cart = f'Добавлено в корзину {cart[str(product_id)]} шт.'
    else:
        in_cart = None

    context = {'product': prod,  # product = prod
               'form': form,
               'in_cart': in_cart}
    return render(request, 'catalog/product_details.html', context)


'''def product_list_view(request):
    products = Product.objects.all()
    objects_count = Product.objects.count()
    context = {'product_list': products, 'objects_count': objects_count}
    print(dict(request.session))
    return render(request, 'catalog/product_list.html', context)
'''


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'product_list'
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)

        paginator = Paginator(self.object_list, self.paginate_by)
        try:
            page = self.request.GET.get('page')
        except:
            page = 1

        try:
            context[self.context_object_name] = paginator.page(page)
        except:
            context[self.context_object_name] = paginator.page(1)

        context['objects_count'] = self.model.objects.count()
        return context

cart/templates/cart/cart.html
{% extends 'root.html' %}
{% load te_func %}
{% load static %}

{% block js %}
    <script src="{% static 'js/cart_functions.js' %}"></script>
{% endblock %}

{% block content %}
    <h2>Товары в корзине:</h2>

    {% for product in products %}
        {% include 'catalog/product_list_item.html' with is_cart=True products=product %}
    {% endfor %}

    <p>Кол-во товаров в корзине: <span class="product-count">{{cart|prod_count}}</span></p>
{% endblock %}

catalog/templates/catalog/product_details.html
{% extends 'root.html' %}
{% block content %}
    <p class="fs-16 font-sans-serif">ID: {{ product.pk }}</p>
    <p class="fs-16 font-sans-serif">Название продукта: {{ product.product_name }}</p>
    <p class="fs-16 font-sans-serif">Название производителя: {{ product.manufacturer_name }}</p>
    <p class="fs-16 font-sans-serif">Гарантия: {{ product.guaranty }} мес.</p>
    <p class="fs-16 font-sans-serif">Количество: {{ product.count }} шт.</p>
    <p class="fs-16 font-sans-serif">Название категории: {{ product.category_name }}</p>
    <hr class="bg-danger">

    <form action="." method="post" class="form">
        {% csrf_token %}
        {% if in_cart %}
          <p>{{in_cart}}</p>
        {% endif %}
        {{ form.as_p }}
        <input class="btn btn-success" type="submit" value="Добавить в корзину"/>
    </form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'root.html' %}
{% block content %}
    {% for products in product_list %}
        {% include 'catalog/product_list_item.html' %}
    {% endfor %}
    <p class="fs-14 font-monospace font-roboto-helvetica">Всего {{ product_list|length }} объектов</p>
{% endblock %}

catalog/templates/catalog/product_list_item.html
{% load te_func %}

<div class="{{products.id}}">
    <a href="{% url 'cat:detail' products.pk %}" style="text-decoration: none; color: black;">
        <p class="fs-16 font-sans-serif">Название продукта: {{ products.product_name  }}</p>
        <p class="fs-16 font-sans-serif">Название производителя: {{ products.manufacturer_name }}</p>
        <p class="fs-16 font-sans-serif">Гарантия: {{ products.guaranty }} мес.</p>
        <p class="fs-16 font-sans-serif">Количество: {{ products.count }}</p>
        <p class="fs-16 font-sans-serif">Принадлежит к категории: {{ products.category_name }}</p>
    </a>
    {% if is_cart %}
        <p class="fs-16 font-sans-serif">Кол-во (в корзине): <span class="product-{{products.id}}-count">{{ cart|get_item:products.id }}</span></p>
        <div>
            <input class="product-{{products.id}}-changed" type="number" value="{{ cart|get_item:products.id }}">
            <input class="product-{{products.id}}-change-btn btn btn-warning btn-change" type="button" value="Изменить">
        </div>
        <input type="submit" class="btn btn-danger prod-{{products.id}} btn-delete" value="Удалить">
    {% endif %}
    <hr class="products_divider">
</div>

templates/root.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>

    {% block js %}
    {% endblock %}

    <title>Document</title>
    <style>
        a {
            text-decoration: none;
            color: #f0f0f0;
            font-size: 16px;
        }

        h1 {
            color: #f0f0f0;
        }

        .fs-16 {
            font-size: 18px;
        }

        .font-sans-serif {
            font-family: sans-serif;
        }

        .font-roboto-helvetica {
            font-family: 'Roboto', 'Helvetica' sans-serif;
        }

        .products_divider {
            border: 1px solid grey;
        }

        .fs-14 {
            font-size: 14px;
        }

    </style>
</head>
<body>
    <header class="navbar m-2 p-2 justify-content-center bg-success justify-content-around">
        <h1 class="font-roboto-helvetica">E-SHOP</h1>
        <nav class="w-25 d-flex justify-content-around">
            <a href="{% url 'cat:list' %}" class="font-helvetica font-sans-serif">Главная</a>
            <a href="{% url 'cat:list' %}" class="font-helvetica font-sans-serif">Товары</a>
            <a href="{% url 'cart:cart' %}">Корзина</a>
        </nav>
    </header>
    <div>
        <div class="border p-3 m-2 bg-light">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <footer>

    </footer>
</body>
</html>